-- AlterTable
ALTER TABLE "RepeatDayTaskCheck" ALTER COLUMN "hour" DROP NOT NULL,
ALTER COLUMN "hour" DROP DEFAULT,
ALTER COLUMN "minute" DROP NOT NULL,
ALTER COLUMN "minute" DROP DEFAULT;

-- AlterTable
ALTER TABLE "RepeatDayTaskWithNotYearInterval" ALTER COLUMN "hour" DROP NOT NULL,
ALTER COLUMN "hour" DROP DEFAULT,
ALTER COLUMN "minute" DROP NOT NULL,
ALTER COLUMN "minute" DROP DEFAULT;

-- AlterTable
ALTER TABLE "RepeatDayTaskWithYearInterval" ALTER COLUMN "hour" DROP NOT NULL,
ALTER COLUMN "hour" DROP DEFAULT,
ALTER COLUMN "minute" DROP NOT NULL,
ALTER COLUMN "minute" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Task" ADD COLUMN     "foodChapter" INTEGER NOT NULL DEFAULT 1;
